### ISSUE TITLE
Create lgsm server error - Do NOT run this script as root

### ISSUE THREAD

**Issue by reelsense** [Vagr9K/ansible-role-lgsm#1]
I'm having a problem executing `linuxgsm.sh` via Ansible. Are there changes needed for the current version of LGSM?

```
TASK [lgsm : Create insserver server] ************************************************************************
task path: /home/user/git/ansible/roles/lgsm/tasks/main.yml:19
fatal: [192.168.1.123]: FAILED! => {"changed": true, "cmd": "/home/lgsm/linuxgsm.sh  insserver", "delta": "0:00:00.012081", "end": "2020-07-11 22:44:37.882162", "msg": "non-zero return code", "rc": 1, "start": "2020-07-11 22:44:37.870081", "stderr": "", "stderr_lines": [], "stdout": "[ FAIL ] Do NOT run this script as root!", "stdout_lines": ["[ FAIL ] Do NOT run this script as root!"]}
```

Relevant code:

https://github.com/Vagr9K/ansible-role-lgsm/blob/d8960e2504fdfd8a7500692880ec665b53b678ad/tasks/main.yml#L17-L24

**Comment by Vagr9K** [comment]
> Are there changes needed for the current version of LGSM?

I believe this exit reason has existed since forever. It looks like Ansible failed to switch to a non-root user set by `lgsm_server_user`.

Do you have `lgsm_server_user` and `lgsm_server_group` properly configured?

Is the issue reproducible with the example playbook provided in the README?

**Comment by reelsense** [comment]
I think I misconfigured something. 

I'm using this ugly unnecessary hack until I find my error:
```
'sudo -H -u {{ lgsm_server_user }} bash -c "bash linuxgsm.sh  {{ lgsm_server_name }}"'
```

Thank you for making this playbook. If you have a donation page or bitcoin address I'd be happy to give you value for value.

**Comment by Vagr9K** [comment]
> Thank you for making this playbook. If you have a donation page or bitcoin address I'd be happy to give you value for value.

Thank you for offering a donation, but there is no need for that. I'm happy that my project is useful for you 😃
